const projectList = [
  {
    id: '1',
    name: 'Keeping track of hundreds of components',
    description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s with the releaLorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s with the release",
    featuredImage: './assets/Snapshoot-Portfolio.png',
    desktopImage: './assets/Snapshoot-Portfolio-desktop.png',
    closeIcon: './assets/Enabled.png',
    technologies: {
      ruby: 'Ruby on rails',
      css: 'css',
      javascript: 'Javascript',
      codekit: 'Codekit',
      github: 'GitHub',
      bootstrap: 'Bootstrap',
      terminal: 'Terminal',
      codepen: 'Codepen',
    },
    liveVersion: 'https://fayob.github.io/portfolio-setup-project/',
    source: 'github.com/fayob/portfolio-setup-project',
  },
  {
    id: '2',
    name: 'Keeping track of hundreds of components',
    description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s with the releaLorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s with the release",
    featuredImage: './assets/Snapshoot-Portfolio.png',
    desktopImage: './assets/Snapshoot-Portfolio-desktop.png',
    closeIcon: './assets/Enabled.png',
    technologies: {
      ruby: 'Ruby on rails',
      css: 'css',
      javascript: 'Javascript',
      codekit: 'Codekit',
      github: 'GitHub',
      bootstrap: 'Bootstrap',
      terminal: 'Terminal',
      codepen: 'Codepen',
    },
    liveVersion: 'https://fayob.github.io/portfolio-setup-project/',
    source: 'github.com/fayob/portfolio-setup-project',
  },
  {
    id: '3',
    name: 'Keeping track of hundreds of components',
    description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s with the releaLorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s with the release",
    featuredImage: './assets/Snapshoot-Portfolio.png',
    desktopImage: './assets/Snapshoot-Portfolio-desktop.png',
    closeIcon: './assets/Enabled.png',
    technologies: {
      ruby: 'Ruby on rails',
      css: 'css',
      javascript: 'Javascript',
      codekit: 'Codekit',
      github: 'GitHub',
      bootstrap: 'Bootstrap',
      terminal: 'Terminal',
      codepen: 'Codepen',
    },
    liveVersion: 'https://fayob.github.io/portfolio-setup-project/',
    source: 'https://github.com/fayob/portfolio-setup-project',
    sourceIcon: './assets/Icon-Export.png',
    liveVersionIcon: './assets/Vector.png',
  },
  {
    id: '4',
    name: 'Keeping track of hundreds of components',
    description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s with the releaLorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s with the release",
    featuredImage: './assets/Snapshoot-Portfolio.png',
    desktopImage: './assets/Snapshoot-Portfolio-desktop.png',
    closeIcon: './assets/Enabled.png',
    technologies: {
      ruby: 'Ruby on rails',
      css: 'css',
      javascript: 'Javascript',
      codekit: 'Codekit',
      github: 'GitHub',
      bootstrap: 'Bootstrap',
      terminal: 'Terminal',
      codepen: 'Codepen',
    },
    liveVersion: 'https://fayob.github.io/portfolio-setup-project/',
    source: 'https://github.com/fayob/portfolio-setup-project',
    sourceIcon: './assets/Icon-Export.png',
    liveVersionIcon: './assets/Vector.png',
  },
  {
    id: '5',
    name: 'Keeping track of hundreds of components',
    description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s with the releaLorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s with the release",
    featuredImage: './assets/Snapshoot-Portfolio.png',
    desktopImage: './assets/Snapshoot-Portfolio-desktop.png',
    closeIcon: './assets/Enabled.png',
    technologies: {
      ruby: 'Ruby on rails',
      css: 'css',
      javascript: 'Javascript',
      codekit: 'Codekit',
      github: 'GitHub',
      bootstrap: 'Bootstrap',
      terminal: 'Terminal',
      codepen: 'Codepen',
    },
    liveVersion: 'https://fayob.github.io/portfolio-setup-project/',
    source: 'https://github.com/fayob/portfolio-setup-project',
    sourceIcon: './assets/Icon-Export.png',
    liveVersionIcon: './assets/Vector.png',
  },
  {
    id: '6',
    name: 'Keeping track of hundreds of components',
    description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s with the releaLorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s with the release",
    featuredImage: './assets/Snapshoot-Portfolio.png',
    desktopImage: './assets/Snapshoot-Portfolio-desktop.png',
    closeIcon: './assets/Enabled.png',
    technologies: {
      ruby: 'Ruby on rails',
      css: 'css',
      javascript: 'Javascript',
      codekit: 'Codekit',
      github: 'GitHub',
      bootstrap: 'Bootstrap',
      terminal: 'Terminal',
      codepen: 'Codepen',
    },
    liveVersion: 'https://fayob.github.io/portfolio-setup-project/',
    source: 'https://github.com/fayob/portfolio-setup-project',
    sourceIcon: './assets/Icon-Export.png',
    liveVersionIcon: './assets/Vector.png',
  },
];

// module.export = projectList;
export default projectList;